from keitaro/ckan:2.9

COPY ext_setup/production.ini ${APP_DIR}
COPY ext_setup/ckanext-mysql2mongodb ${SRC_DIR}/ckanext-mysql2mongodb

# FROM python:3
# CMD [${SRC_DIR}+"/ckanext-mysql2mongodb/run_setup.py"]
# ENTRYPOINT ["python3"]
